### ISSUE TITLE
AGU24 Town Hall flyer

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-sep#53]
Ashley
  1 day ago
Good morning! I have two drafts of the SNWG town hall poster ready for review [here](https://www.canva.com/design/DAGJWbz-h78/Ylo_r6gRSjOPNKtKR7nrAg/edit?utm_content=DAGJWbz-h78&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).

Pontus
  1 day ago
Thanks! They both look good to me. We can probably remove the call for abstracts at the bottom as they are not needed for town halls.
:+1::skin-tone-2:
1

Pontus
  [1 day ago](https://teamdsig.slack.com/archives/C05PV59STC7/p1719850533251109?thread_ts=1719850220.483779&cid=C05PV59STC7)
The same for the QR code for submitting an abstract

Ashley
  1 day ago
Replace with "learn more" and a link to the website when it's available?

Pontus
  [1 day ago](https://teamdsig.slack.com/archives/C05PV59STC7/p1719852366099149?thread_ts=1719850220.483779&cid=C05PV59STC7)
yes, that sounds good!

Natasha Sadoff
  1 day ago
Looks great, I just added a couple of spaces. I like the lighter, second version!

Pontus
  21 hours ago
I removed the blue banner at the bottom and made the text a bit bigger. I also listed us all as "Conveners" rather than primary and secondary. These changes are reflected in the version on "Page 2," titled "First choice updated." Feedback?

Natasha Sadoff
  19 hours ago
Also seems fine to me! Though the QR code goes to AGU the abstraction submission page. We aren't accepting abstracts right? So what do we want that code to lead to? Also, do we have schedule info yet?

Pontus
  18 hours ago
We'll update the QR code to link to the SNWG  webiste

**Comment by CherrelleTucker** [comment]
Pontus
  4:26 PM
I updated the town hall flyer. How can we determine if we can use the meatball? STRIVES?

Rachel Wyatt
:speech_balloon:  [4:28 PM](https://teamdsig.slack.com/archives/C01TJ48A5QQ/p1724362118932649)
[@Pontus](https://teamdsig.slack.com/team/U03JG3X1VB4)
 I can check with Aries

**Comment by CherrelleTucker** [comment]
[2024-08-29  SNWG SEP Weekly Meeting](https://docs.google.com/document/d/1DWR2XClGZ4zPvOgFkAuQNKArVDjvqmBDGA3OYNpBcTI/edit)

Current status: https://www.canva.com/design/DAGJWbz-h78/Ylo_r6gRSjOPNKtKR7nrAg/edit?utm_content=DAGJWbz-h78&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 
Next steps: pending AGU time/location announcement to complete.

**Comment by rwyatt19** [comment]
AGU time/location info added. This should be done!
